# -- marts/obt_sales.yml --

version: 2
models:
- name: obt_sales
  description: "Table contenant toutes les informations nécessaires pour identifier une ligne de vente"
  columns:
  - name: vente_id
    description: "id de fact_ventes"
  - name: annees
  - name: mois
  - name: jour
  - name: pu
  - name: qte
  - name: facture_id
    description: "id de fact_factures"
  - name: facture_code
  - name: qte_totale
  - name: total_amount
  - name: total_paid
  - name: category_name
  - name: book_code
  - name: book_name
  - name: isbn_10
  - name: isbn_13
  - name: customer_code
  - name: nom
    description: "Nom complet du client"

exposures:
  - name: resume_ventes
    type: dashboard
    maturity: high
    url: https://app.snowflake.com/
    description: "Tableau de bord de suivi des performances de la boutique"
    depends_on:
      - ref('obt_sales')
    owner:
      name: "Moutsita"
      email: "moutsitarovincy@gmail.com"

